### PR TITLE
Recoded the library in typescript

### PR DESCRIPTION
**Pull request by Didas-git**
I decided to remake the library in typescript and improve the types of it because writing every single type manually is a pain

### CODE REVIEW

**Comment by Didas-git** [comment]
I pushed the typescript to my fork of the repository if you guys want to check it

**Review by orsou — COMMENTED** [review]
Looks great, but why not make it a seperate repository?

**Comment by Didas-git** [comment]
> Looks great, but why not make it a seperate repository?

To be honest, i was working on other ways of making the wrapper and i decided to give a try and recode the original one that inspired me to do it. At the beggining i was not going to make a pr specially bcz the api is already on version 3 but yeah.
I might update the pr to version 3 once im done testing with it but i dont know if the owner of the package/repo wants it

**Comment by orsou** [comment]
Maybe Ronin could make a seperate repo in the Nekos-life org for you. @TheCyberRonin

**Comment by TheCyberRonin** [comment]
I'm not sure there's really a need for that tbh. I saw this a bit ago and forgot to reply.

This is something you'd ask a project maintainer instead of just doing and putting in a PR.

**Comment by orsou** [comment]
> This is something you'd ask a project maintainer instead of just doing and putting in a PR.

That's why I suggested a seperate repo, if you don't want to put it into the org they could probably create their own repo right?

**Comment by TheCyberRonin** [comment]
I'm also saving V3 for when there's some nice stuff added with V3 of the API. 

I also don't want to have to use TS to add features to or fix a library that has its main intention of being lightweight and minimal.

**Comment by Didas-git** [comment]
Fair point, but i already had it done so i decided to make a pr since i dont know any other method (other than email) that i could contact the mantainer

**Comment by orsou** [comment]
> I'm also saving V3 for when there's some nice stuff added with V3 of the API.
> 
> I also don't want to have to use TS to add features to or fix a library that has its main intention of being lightweight and minimal.

Okay, makes sense.

**Pull request closed without merging**
